[package]
name = "piston-example-freetype"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[[bin]]
name = "piston-example-freetype"
path = "src/main.rs"

[dependencies]
piston = "0.32.0"
piston2d-opengl_graphics = "0.44.0"
piston2d-graphics = "0.21.1"
pistoncore-sdl2_window = "0.43.0"
freetype-rs = "0.13.0"
find_folder = "0.3.0"
